language: java

jdk:
  - oraclejdk8

before_script:
  # This will download and run the Devfactory Dependency Analyser
  - git clone https://github.com/aditya-travis/devfactory-travis-plugins.git
  - python devfactory-travis-plugins/devfactory-travis-plugin.py

script: mvn test javadoc:javadoc

after_success:
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml coveralls:cobertura
