language: java

jdk:
  - oraclejdk8

before_script:
  # This will download and run the Devfactory Dependency Analyser
  - git clone https://github.com/DevFactory/tpls-travis-plugin.git
  - python tpls-travis-plugin/tpls-travis-plugin.py

script: mvn test javadoc:javadoc

after_success:
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml coveralls:cobertura

